export const projects = [
    {
        name: "Portfolio",
        date: "January 2020",
        links: ["https://ctlachance.com", "https://github.com/CTLaChance/Portfolio"],
        summary: "I decided to create a portfolio site as a way to practice my front-end development skills, particularly React and JS/Typescript. The project auto-builds on and is hosted with Google Cloud. Commits to the master branch trigger the deployment of a production build of the site.",

        card: "/assets/projects/portfolio/0.png",
        media_folder: "/assets/projects/portfolio",
        media: require.context('../../public/assets/projects/portfolio', false, /\.jpg|png/).keys(),
    },
    {
        name: "ARE Website",
        date: "December 2016",
        links: ["https://areducators.com", "https://github.com/CTLaChance/AREWebsite"],
        summary: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",

        card: "/assets/projects/arewebsite/card.png",
        media_folder: "/assets/projects/arewebsite",
        media: require.context('../../public/assets/projects/arewebsite', false, /\.jpg|png/).keys(),
    },
    {
        name: "Pharaoh Sun",
        date: "March 2018",
        links: ["https://playags.com/portfolio/pharaoh-sun/"],
        summary: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",

        card: "/assets/projects/pharaohsun/card.jpg",
        media_folder: "/assets/projects/pharaohsun",
        media: require.context('../../public/assets/projects/pharaohsun', false, /\.jpg|png/).keys(),
    },
    {
        name: "Wild Tiki",
        date: "October 2018",
        links: ["https://playags.com/portfolio/wild-tiki/"],
        summary: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
        
        card: "/assets/projects/wildtiki/card.jpg",
        media_folder: "/assets/projects/wildtiki",
        media: require.context('../../public/assets/projects/wildtiki', false, /\.jpg|png/).keys(),
    },
    {
        name: "Unreleased Project",
        date: "October 2019",
        links: [""],
        summary: "This is the 3rd game I developed at AGS,LLC. This project has not been released and is currently under NDA.",
        card: "/assets/projects/REDACTED.jpg",
        media_folder: "",
        media: [],
    },
    {
        name: "Unreleased Project",
        date: "April 2019",
        links: [""],
        summary: "This is the 4th game I developed at AGS,LLC. This project has not been released and is currently under NDA.",
        card: "/assets/projects/REDACTED.jpg",
        media_folder: "",
        media: [],
    },
    {
        name: "Unreleased Project",
        date: "April 2019",
        links: [""],
        summary: "This is the 5th game I developed at AGS,LLC. This project has not been released and is currently under NDA.",
        card: "/assets/projects/REDACTED.jpg",
        media_folder: "",
        media: [],
    },
    {
        name: "Unreleased Project",
        date: "July 2019",
        links: [""],
        summary: "This is the 6th game I developed at AGS,LLC. This project has not been released and is currently under NDA.",
        card: "/assets/projects/REDACTED.jpg",
        media_folder: "",
        media: [],
    },
    {
        name: "Unreleased Project",
        date: "July 2019",
        links: [""],
        summary: "This is the 7th game I developed at AGS,LLC. This project has not been released and is currently under NDA.",
        card: "/assets/projects/REDACTED.jpg",
        media_folder: "",
        media: [],
    },
    {
        name: "Unreleased Project",
        date: "January 2020",
        links: [""],
        summary: "This is the 8th game I developed at AGS,LLC. This project has not been released and is currently under NDA.",
        card: "/assets/projects/REDACTED.jpg",
        media_folder: "",
        media: [],
    },
    {
        name: "Unreleased Project",
        date: "January 2020",
        links: [""],
        summary: "This is the 9th game I developed at AGS,LLC. This project has not been released and is currently under NDA.",
        card: "/assets/projects/REDACTED.jpg",
        media_folder: "",
        media: [],
    },
];