export const projects = [
    {
        name: "Portfolio",
        date: "January 2020",
        links: ["https://ctlachance.com", "https://github.com/CTLaChance/Portfolio"],
        summary: "I decided to create a portfolio site as a way to practice my front-end development skills, particularly React and JS/Typescript. The project auto-builds on and is hosted with Google Cloud. Commits to the master branch trigger the deployment of a production build of the site.",

        card: "/assets/projects/portfolio/0.png",
        media_folder: "/assets/projects/portfolio",
        media: require.context('../../public/assets/projects/portfolio', false, /\.jpg|png/).keys(),
    },
    {
        name: "A.R.E Website",
        date: "December 2016",
        links: ["https://areducators.com", "https://github.com/CTLaChance/AREWebsite"],
        summary: "This is the 2nd version of the Algebra Readiness Educator, LLC website. This redesign was a significant overhaul of the first revision of the website which was originally created using Adobe Dreamweaver. I am currently in the process of updating once more using the lessons and technology I've acquired since then.",

        card: "/assets/projects/arewebsite/0.png",
        media_folder: "/assets/projects/arewebsite",
        media: require.context('../../public/assets/projects/arewebsite', false, /\.jpg|png/).keys(),
    },
    {
        name: "Pharaoh Sun",
        date: "March 2018",
        links: ["https://playags.com/portfolio/pharaoh-sun/"],
        summary: "Pharaoh Sun was the 1st game I worked on at AGS. This game features expanding reels in the freespin games, a 'pick 3' progressive pick game, and a PowerXStream payout evaluation.",

        card: "/assets/projects/pharaohsun/0.png",
        media_folder: "/assets/projects/pharaohsun",
        media: require.context('../../public/assets/projects/pharaohsun', false, /\.jpg|png/).keys(),
    },
    {
        name: "Wild Tiki",
        date: "October 2018",
        links: ["https://playags.com/portfolio/wild-tiki/"],
        summary: "Wild Tiki was the 2nd game I worked on at AGS. This game features expanding wilds in the freespin games, a 'pick 3' progressive pick game, and a PowerXStream payout evaluation.",
        
        card: "/assets/projects/wildtiki/0.png",
        media_folder: "/assets/projects/wildtiki",
        media: require.context('../../public/assets/projects/wildtiki', false, /\.jpg|png/).keys(),
    },
    {
        name: "Unreleased Project",
        date: "October 2019",
        links: [""],
        summary: "This is the 3rd game I developed at AGS,LLC. This project has not been released and is currently under NDA.",
        card: "/assets/projects/REDACTED.jpg",
        media_folder: "",
        media: [],
    },
    {
        name: "Unreleased Project",
        date: "April 2019",
        links: [""],
        summary: "This is the 4th game I developed at AGS,LLC. This project has not been released and is currently under NDA.",
        card: "/assets/projects/REDACTED.jpg",
        media_folder: "",
        media: [],
    },
    {
        name: "Unreleased Project",
        date: "April 2019",
        links: [""],
        summary: "This is the 5th game I developed at AGS,LLC. This project has not been released and is currently under NDA.",
        card: "/assets/projects/REDACTED.jpg",
        media_folder: "",
        media: [],
    },
    {
        name: "Unreleased Project",
        date: "July 2019",
        links: [""],
        summary: "This is the 6th game I developed at AGS,LLC. This project has not been released and is currently under NDA.",
        card: "/assets/projects/REDACTED.jpg",
        media_folder: "",
        media: [],
    },
    {
        name: "Unreleased Project",
        date: "July 2019",
        links: [""],
        summary: "This is the 7th game I developed at AGS,LLC. This project has not been released and is currently under NDA.",
        card: "/assets/projects/REDACTED.jpg",
        media_folder: "",
        media: [],
    },
    {
        name: "Unreleased Project",
        date: "January 2020",
        links: [""],
        summary: "This is the 8th game I developed at AGS,LLC. This project has not been released and is currently under NDA.",
        card: "/assets/projects/REDACTED.jpg",
        media_folder: "",
        media: [],
    },
    {
        name: "Unreleased Project",
        date: "January 2020",
        links: [""],
        summary: "This is the 9th game I developed at AGS,LLC. This project has not been released and is currently under NDA.",
        card: "/assets/projects/REDACTED.jpg",
        media_folder: "",
        media: [],
    },
];