name: AutoDeploy

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.10.0
      uses: actions/setup-node@v1
      with:
        node-version: "12.10.0"
    - name: Install Packages
      run: npm install
    - name: Deploy to GH Pages
      run: npm run deploy
